### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by Gertje823** [mikosjakub/askfm-scrapper#1]
A few months ago I downloaded a couple of profiles with this awesome tool. I wanted to download another profile today but then I got this error:
```
Retrieving next page link
No "Next" link found. Retrieving done.
Saving to JSON
Traceback (most recent call last):
  File "menu.py", line 70, in <module>
    menu()
  File "menu.py", line 54, in menu
    retrieve(**CONFIG)
  File "\askfm-scrapper-master\app.py", line 116, in retrieve
  File "\askfm-scrapper-master\app.py", line 125, in perform_file_operations
  File "\askfm-scrapper-master\app.py", line 139, in save_to_json
  File "\askfm-scrapper-master\answer.py", line 18, in question
AttributeError: 'NoneType' object has no attribute 'string'
```
I am running python 3.8.7 on windows.

**Comment by adzkar** [comment]
i have solved this issue by create a pr at this #2
